"""Add column last_name to User model

Revision ID: 5471a632b4af
Revises: 1a31ce608336
Create Date: 2024-09-10 08:36:07.044320

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5471a632b4af'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hancharacter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('han_character', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('english_translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nom_character', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quoc_ngu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hancharacter_english_translation'), 'hancharacter', ['english_translation'], unique=False)
    op.create_index(op.f('ix_hancharacter_han_character'), 'hancharacter', ['han_character'], unique=False)
    op.create_index(op.f('ix_hancharacter_nom_character'), 'hancharacter', ['nom_character'], unique=False)
    op.create_index(op.f('ix_hancharacter_quoc_ngu'), 'hancharacter', ['quoc_ngu'], unique=False)
    op.create_index(op.f('ix_hancharacter_source_text'), 'hancharacter', ['source_text'], unique=False)
    op.create_table('hantext',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('han_character', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('english_translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nom_character', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quoc_ngu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hantext_english_translation'), 'hantext', ['english_translation'], unique=False)
    op.create_index(op.f('ix_hantext_han_character'), 'hantext', ['han_character'], unique=False)
    op.create_index(op.f('ix_hantext_nom_character'), 'hantext', ['nom_character'], unique=False)
    op.create_index(op.f('ix_hantext_quoc_ngu'), 'hantext', ['quoc_ngu'], unique=False)
    op.create_index(op.f('ix_hantext_source_text'), 'hantext', ['source_text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hantext_source_text'), table_name='hantext')
    op.drop_index(op.f('ix_hantext_quoc_ngu'), table_name='hantext')
    op.drop_index(op.f('ix_hantext_nom_character'), table_name='hantext')
    op.drop_index(op.f('ix_hantext_han_character'), table_name='hantext')
    op.drop_index(op.f('ix_hantext_english_translation'), table_name='hantext')
    op.drop_table('hantext')
    op.drop_index(op.f('ix_hancharacter_source_text'), table_name='hancharacter')
    op.drop_index(op.f('ix_hancharacter_quoc_ngu'), table_name='hancharacter')
    op.drop_index(op.f('ix_hancharacter_nom_character'), table_name='hancharacter')
    op.drop_index(op.f('ix_hancharacter_han_character'), table_name='hancharacter')
    op.drop_index(op.f('ix_hancharacter_english_translation'), table_name='hancharacter')
    op.drop_table('hancharacter')
    # ### end Alembic commands ###
